# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8288f728fa3eaa4bcdc770bae766990214ad164b918698239ff1eb8e54e9769b2c7b6a9579ae1a3b71203023b36027737326234c781ef16965f3bf587ed45e63

test:
  secret_key_base: 26f6a2b09089ccbf2c1895fd85abcb14d8bee21ee1baf6c59dc18ae3932fb9bd831e8b8d6b411ffed67b736c1a53b31a7f47b9b90fc28676394effe788fe2f26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
